set(CPP_FILES
    CemrgCommandLine.cpp
    CemrgCommonUtils.cpp
    CemrgMeasure.cpp
    CemrgScar3D.cpp
    CemrgStrains.cpp
    CemrgPower.cpp
    CemrgAtriaClipper.cpp
    CemrgAtrialTools.cpp
    CemrgScarAdvanced.cpp
    CemrgTests.cpp
    CemrgFourChamberTools.cpp
    CemrgFourChamberCmd.cpp
    CemrgMultilabelSegmentationUtils.cpp
    CemrgMeshPointSelector.cpp
    CemrgAtrialModellingToolCmd.cpp
)

set(UI_FILES
)

set(MOC_H_FILES
  include/CemrgAtriaClipper.h
  include/CemrgAtrialTools.h
  include/CemrgCommandLine.h
  include/CemrgCommonUtils.h
  include/CemrgMeasure.h
  include/CemrgScar3D.h
  include/CemrgStrains.h
  include/CemrgPower.h
  include/CemrgScarAdvanced.h
  include/CemrgMultilabelSegmentationUtils.h
  include/CemrgAtrialModellingToolCmd.h
  include/CemrgFourChamberTools.h
  include/CemrgFourChamberCmd.h
  include/CemrgMeshPointSelector.h
  include/FourChamberCommon.h
)

set(RESOURCE_FILES
)
