name: CemrgApp Tests and Code Coverage

on: [push, pull_request]

jobs:
  Test-Coverage:
    runs-on: ubuntu-18.04
    steps:
    - name: Download precompiled Build folder
      run: |
        wget -q -O Build.zip https://emckclac-my.sharepoint.com/:u:/g/personal/k2143219_kcl_ac_uk/Ef5Vu6za325GoIIStbIcmg4BgWlVBGtUx6jp1GrxNLYrFw?download=1
        7z x Build.zip
        rm Build.zip
        sudo mv Build /
    
    - name: Install missing packages
      run: |
        sudo apt update
        sudo DEBIAN_FRONTEND=noninteractive apt install libxt-dev libtiff5-dev libfontconfig1 mesa-common-dev libglu1-mesa-dev libxcomposite1 libxcursor1 libxrender1 libxi6 libxtst6 libasound2 libnspr4 libnss3 libxkbcommon-dev libxkbcommon-x11-dev doxygen git cmake python3-pip gcc-6 g++-6 -y
        sudo apt remove --auto-remove icu-devtools libicu-dev -y
    
    - name: Install Qt
      run: |
        sudo pip3 install --upgrade setuptools
        sudo pip3 install aqtinstall
        sudo aqt install --outputdir /Qt 5.12.10 linux desktop -m qtcharts qtnetworkauth qtpurchasing qtdatavis3d qtscript qtvirtualkeyboard qtwebengine qtwebglplugin
    
    - name: Clone MITK
      run: sudo git clone --branch v2018.04.2 https://phabricator.mitk.org/source/mitk.git /MITK

    - name: Clone CemrgApp
      uses: actions/checkout@v2
      with:
        path: CemrgApp

    - name: Move CemrgApp to root
      run: sudo mv CemrgApp /
    
    - name: Build
      working-directory: /Build
      run: make -j4

    - name: Test
      working-directory: /Build/MITK-build
      run: ctest -R Cemrg -V

    - name: Code Coverage
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        functionalities: coveragepy
        root_dir: /CemrgApp/
        gcov_root_dir: /Build/MITK-build
        directory: ${{ github.workspace }}
